# Display Name of the workflow
name: Static Analysis - Advanced Secret Scan

# When this workflow triggers
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Allow this workflow to be called from another workflow
    workflow_call:

    # Run the unit tests on every change
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

# Define each session of execution that should be executed
jobs:
    SecretScan:
        # Display name of the job
        name: Scan for Secrets

        # Operating system filter for the runners
        runs-on: ubuntu-latest

        # Sets the scopes available to the github_token injected to the GH Actions runner
        permissions:
            contents: read

        steps:
            # Calculate the depth and branch for checkout optimization
            - name: Calculate Checkout Depth and Branch
              shell: bash
              run: |
                  if [ "${{ github.event_name }}" == "push" ]; then
                    echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
                    echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
                  fi
                  if [ "${{ github.event_name }}" == "pull_request" ]; then
                    echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
                    echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
                  fi

            # Checks-out your repository under $GITHUB_WORKSPACE
            - uses: actions/checkout@v5
              with:
                ref: ${{env.branch}}
                fetch-depth: ${{env.depth}}

            # Run trufflehog
            - name: Scan for Secrets
              uses: trufflesecurity/trufflehog@0f58ae7c5036094a1e3e750d18772af92821b503
              with:
                extra_args: --github-actions --results=verified,unknown
